const NOTIFY_EMAIL = "你的Email@gmail.com";
const API_TOKEN = "請改成一串自訂亂碼例如hf-2026-x7k9q2";
const DRIVE_FOLDER = "報名繳費憑證";
const RETENTION_MONTHS = 12;
const TZ = "Asia/Taipei";
const BOOKING_START_AT = "2026-07-07T10:00:00+08:00";
const OPEN_WEEKDAYS = [0,1,2,3,4,5];
const CLOSED_WEEKDAYS = [6];
const DEFAULT_OPEN_WEEKS = 8;
const CLOSED_DATES = [];
const COURSES = [
  {series:"心村限定｜Helori 香氣探索所",course:"單人調香探索課 10ML",price:990,capacity:10,times:["09:00–11:00","11:00–13:00","14:00–16:00","16:00–18:00"],mode:"single"},
  {series:"心村限定｜Helori 香氣探索所",course:"單人調香探索課 50ML",price:1800,capacity:10,times:["09:00–11:00","11:00–13:00","14:00–16:00","16:00–18:00"],mode:"single"},
  {series:"H.FUGUE ATELIER 專業調香師課程",course:"01 氣味藝術序曲",price:3500,capacity:6,times:["10:00–16:00"],mode:"single"},
  {series:"韓國 KPIA 調香協會系列",course:"KPIA大韓專業調香師課程",price:39000,capacity:4,times:["09:00–11:00","11:00–13:00","14:00–16:00","16:00–18:00"],mode:"multiple",max:8},
  {series:"韓國 KPIA 調香協會系列",course:"KPIA 專業調香師雙證書課（優惠加購無酒精香水證書）",price:44000,capacity:4,times:["09:00–11:00","11:00–13:00","14:00–16:00","16:00–18:00"],mode:"multiple",max:8},
  {series:"韓國 KPIA 調香協會系列",course:"KPIA無酒精香水課程",price:6500,capacity:4,times:["10:00–15:00"],mode:"single"}
];
function doGet(e){if(e.parameter.action==="slots")return json({slots:getOpenSlots()});return json({ok:true,service:"hana-booking"});}
function doPost(e){const lock=LockService.getScriptLock();lock.waitLock(15000);try{let d;try{d=JSON.parse(e.postData.contents)}catch(_){return json({ok:false,error:"BAD_REQUEST"})}if(d.website)return json({ok:true,bookingId:"HF-000000-000"});if(d.token!==API_TOKEN)return json({ok:false,error:"BAD_REQUEST"});const v=validate(d);if(v)return json({ok:false,error:v});const ids=normalizeSlotIds(d);const slots=getOpenSlots();const map={};slots.forEach(s=>map[s.id]=s);const selected=[];for(let i=0;i<ids.length;i++){const s=map[ids[i]];if(!s||s.booked>=s.capacity)return json({ok:false,error:"SLOT_FULL"});selected.push(s)}const first=selected[0],meta=courseMeta(first.series,first.course);if(!meta)return json({ok:false,error:"BAD_REQUEST"});if(meta.mode==="single"&&selected.length!==1)return json({ok:false,error:"BAD_REQUEST"});if(meta.mode==="multiple"&&selected.length>(meta.max||8))return json({ok:false,error:"BAD_REQUEST"});if(!selected.every(s=>s.series===first.series&&s.course===first.course))return json({ok:false,error:"BAD_REQUEST"});let proofUrl="";if(d.proofBase64){const folder=getOrCreateFolder(DRIVE_FOLDER);const tag=ids[0]+"_"+Utilities.formatDate(new Date(),TZ,"yyyyMMdd-HHmmss");const blob=Utilities.newBlob(Utilities.base64Decode(d.proofBase64),"image/jpeg",tag+".jpg");const file=folder.createFile(blob);file.setSharing(DriveApp.Access.PRIVATE,DriveApp.Permission.NONE);proofUrl=file.getUrl()}const ss=SpreadsheetApp.getActiveSpreadsheet();const sheet=getOrCreateSheet_(ss,"報名",["報名編號","報名時間","場次ID","場次","課程","方案","姓名","電話","Email","LINE","繳費方式","後五碼","憑證連結","備註","狀態"]);const bookingId="HF-"+Utilities.formatDate(new Date(),TZ,"yyMMdd")+"-"+String(sheet.getLastRow()).padStart(3,"0");const slotsText=selected.map(s=>s.date+" "+s.time).join(" / ");sheet.appendRow([bookingId,Utilities.formatDate(new Date(),TZ,"yyyy-MM-dd HH:mm"),ids.join(" | "),slotsText,first.course,"",d.name,"'"+d.phone,d.email||"",d.line||"",d.method,d.last5?"'"+d.last5:"",proofUrl,d.note||"","待對帳"]);MailApp.sendEmail({to:NOTIFY_EMAIL,subject:"【新報名待對帳】"+first.course,htmlBody:"<p>有一筆新的課程報名,場次已鎖定,請進行對帳。</p><table cellpadding='4' style='font-size:14px'><tr><td>報名編號</td><td><b>"+escHtml(bookingId)+"</b></td></tr><tr><td>課程</td><td>"+escHtml(first.course)+"</td></tr><tr><td>場次</td><td>"+escHtml(slotsText)+"</td></tr><tr><td>姓名</td><td>"+escHtml(d.name)+"</td></tr><tr><td>電話</td><td>"+escHtml(maskPhone(d.phone))+"</td></tr><tr><td>繳費方式</td><td>"+escHtml(d.method)+"</td></tr><tr><td>金額</td><td>NT$ "+Number(first.price).toLocaleString()+"</td></tr></table><p>完整聯絡資料、後五碼與繳費憑證請至試算表查看:<br><a href='"+ss.getUrl()+"'>開啟報名管理試算表</a></p>"});return json({ok:true,bookingId})}catch(err){console.error(err);return json({ok:false,error:"SERVER_ERROR"})}finally{lock.releaseLock()}}
function validate(d){d.slotId=str(d.slotId);d.name=str(d.name);d.phone=str(d.phone);d.email=str(d.email);d.line=str(d.line);d.method=str(d.method);d.last5=str(d.last5);d.note=str(d.note);const ids=normalizeSlotIds(d);if(!ids.length||ids.length>8)return"BAD_REQUEST";if(ids.some(id=>!id||id.length>140))return"BAD_REQUEST";if(!d.name||d.name.length>50)return"BAD_REQUEST";if(!/^[0-9+\-() ]{7,20}$/.test(d.phone))return"BAD_REQUEST";if(d.email&&(d.email.length>100||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email)))return"BAD_REQUEST";if(d.line.length>50||d.note.length>800)return"BAD_REQUEST";if(["轉帳","刷卡","分期"].indexOf(d.method)===-1)return"BAD_REQUEST";if(d.method==="轉帳"&&!/^\d{5}$/.test(d.last5))return"BAD_REQUEST";if(!d.proofBase64)return"BAD_REQUEST";if(d.proofBase64.length>8000000)return"FILE_TOO_LARGE";return null}
function normalizeSlotIds(d){if(Array.isArray(d.slotIds))return d.slotIds.map(x=>str(x)).filter(Boolean);if(typeof d.slotIds==="string")return d.slotIds.split(/[|,，、\s]+/).map(x=>str(x)).filter(Boolean);return d.slotId?[str(d.slotId)]:[]}
function getOpenSlots(){const today=Utilities.formatDate(new Date(),TZ,"yyyy-MM-dd");const generated=generateSlots_();const manual=readManualSlots_();const counts=getBookedCounts_();const map={};generated.forEach(s=>map[s.id]=s);manual.forEach(s=>{if(s.status==="關閉")delete map[s.id];else if(s.status==="開放")map[s.id]=Object.assign(map[s.id]||{},s)});return Object.keys(map).map(id=>{const s=map[id];s.booked=counts[id]||0;return s}).filter(s=>s.date>=today&&s.status!=="關閉")}
function generateSlots_(){const slots=[];const start=parseDate_(BOOKING_START_AT.slice(0,10));const today=new Date();today.setHours(0,0,0,0);const anchor=start>today?start:today;const end=new Date(anchor);end.setDate(end.getDate()+DEFAULT_OPEN_WEEKS*7);for(let d=new Date(anchor);d<=end;d.setDate(d.getDate()+1)){const ds=Utilities.formatDate(d,TZ,"yyyy-MM-dd");const dow=Number(Utilities.formatDate(d,TZ,"u"))%7;if(!isDateOpen_(ds,dow))continue;COURSES.forEach(c=>c.times.forEach((time,i)=>{if(!isTimeOpenForDay_(dow,time))return;slots.push({id:makeSlotId_(c,ds,time,i),series:c.series,course:c.course,variant:"",date:ds,time:time,price:Number(c.price),capacity:Number(c.capacity),booked:0,status:"開放"})}))}return slots}
function isTimeOpenForDay_(dow,time){if(dow!==3)return true;return getEndHour_(time)<=14}
function getEndHour_(time){const parts=String(time).split("–");const end=parts[1]||parts[0]||"";const hm=end.split(":").map(Number);return (hm[0]||0)+((hm[1]||0)/60)}
function readManualSlots_(){const ss=SpreadsheetApp.getActiveSpreadsheet();const sheet=ss.getSheetByName("場次");if(!sheet)return[];const v=sheet.getDataRange().getValues();if(v.length<=1)return[];return v.slice(1).map(r=>({id:String(r[0]||""),series:String(r[1]||""),course:String(r[2]||""),variant:String(r[3]||""),date:r[4] instanceof Date?Utilities.formatDate(r[4],TZ,"yyyy-MM-dd"):String(r[4]||""),time:String(r[5]||""),price:Number(r[6]||0),capacity:Number(r[7]||0),status:String(r[8]||"")})).filter(s=>s.id)}
function getBookedCounts_(){const ss=SpreadsheetApp.getActiveSpreadsheet();const sheet=ss.getSheetByName("報名");if(!sheet)return{};const rows=sheet.getDataRange().getValues();if(rows.length<=1)return{};const c={};rows.slice(1).forEach(r=>{const raw=String(r[2]||""),status=String(r[14]||"");if(!raw||status==="已取消")return;raw.split(/\s*\|\s*|[,，、]/).map(x=>x.trim()).filter(Boolean).forEach(id=>c[id]=(c[id]||0)+1)});return c}
function courseMeta(series,course){return COURSES.find(c=>c.series===series&&c.course===course)||null}
function makeSlotId_(c,date,time,i){return (slug_(c.series)+"-"+slug_(c.course)+"-"+date+"-"+String(i+1).padStart(2,"0")).slice(0,120)}
function slug_(s){return String(s).replace(/[^A-Za-z0-9\u4e00-\u9fa5]+/g,"-").replace(/^-|-$/g,"")}
function isDateOpen_(ds,dow){return CLOSED_DATES.indexOf(ds)===-1&&CLOSED_WEEKDAYS.indexOf(dow)===-1&&OPEN_WEEKDAYS.indexOf(dow)!==-1}
function parseDate_(ds){const p=String(ds).split("-").map(Number);return new Date(p[0],p[1]-1,p[2])}
function getOrCreateFolder(name){const it=DriveApp.getFoldersByName(name);return it.hasNext()?it.next():DriveApp.createFolder(name)}
function getOrCreateSheet_(ss,name,headers){let sheet=ss.getSheetByName(name);if(!sheet){sheet=ss.insertSheet(name);sheet.appendRow(headers)}return sheet}
function maskPhone(p){p=String(p||"");return p.length<=6?p:p.slice(0,4)+"***"+p.slice(-3)}
function str(x){return typeof x==="string"?x.trim():""}
function escHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function json(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON)}